<a href="https://colab.research.google.com/github/dogterbox/datafun/blob/master/_foo/k_fold.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from sklearn.model_selection import KFold
import numpy as np
X = np.array([[1, 1], [2, 2], [3, 3], [4, 4], [5, 5], [6, 6], [7, 7], [8, 8], [9, 9], [10, 10],[9, 9], [10, 10]])
y = np.array([1, 2, 3, 4,5,6,7,8,9,10])

In [3]:
kf = KFold(n_splits=3)
kf.get_n_splits(X)
# print(kf)

for train_index, test_index in kf.split(X):
  print("TRAIN:", train_index, "TEST:", test_index)
  print(X[test_index])

TRAIN: [ 4  5  6  7  8  9 10 11] TEST: [0 1 2 3]
[[1 1]
 [2 2]
 [3 3]
 [4 4]]
TRAIN: [ 0  1  2  3  8  9 10 11] TEST: [4 5 6 7]
[[5 5]
 [6 6]
 [7 7]
 [8 8]]
TRAIN: [0 1 2 3 4 5 6 7] TEST: [ 8  9 10 11]
[[ 9  9]
 [10 10]
 [ 9  9]
 [10 10]]
